### PR TITLE
added 3161

### PR DESCRIPTION
**Pull request by maseology**
Not sure if you're interested in growth, but I'm using you're package in Canada and will be adding more projections.  Thanks for the fork!

### CODE REVIEW

**Comment by lgln-mw** [comment]
Hi maseology, I'm open to pull requests! But I can only merge them if you don't change the README.
Maybe you could create a new branch for the pull request, just with the code changes?
Thanks a lot:)

**Comment by wroge** [comment]
Hi maseology, I'm open to pull requests! But I can only merge them if you don't change the README.
Maybe you could create a new branch for the pull request, just with the code changes?
Thanks a lot:)

**Comment by maseology** [comment]
I couldn't branch, GitHub suggested I fork.  So I reverted the readme back to the originial.  See if that works. If not, we close the request I guess??

**Review by wroge — APPROVED** [review]
Thanks!

**Pull request merged**
